### ISSUE TITLE
Problem when creating a slider inside a uib-tabset 

### ISSUE THREAD

**Issue by cdparra** [enkodellc/angular-multi-slider#1]
[Plunkr Example](http://plnkr.co/edit/dQaJAJzOcKOKA18m25hW?p=preview)

When I use the multi-slider directive inside a uib-tab, the slider appears first with all the handles one on top of another (i.e., all the internal widths = 0px) 
![image](https://cloud.githubusercontent.com/assets/630150/11070544/022b0b4a-8791-11e5-9a4d-24b744cfa28c.png)

Only after clicking on one of the handles, the slider appears with the hanndles in the right positions

![image](https://cloud.githubusercontent.com/assets/630150/11070570/28c064bc-8791-11e5-843d-647e807f9332.png)

**Comment by enkodellc** [comment]
I have not tested with the uib tab yet. I can recreate the issue but none of my initial ideas have worked.   I don't have the time to fix till later. If you want to take a stab at it I would look into uib tab related directive issues: https://github.com/angular-ui/bootstrap/wiki/FAQ#my-input--select-element-doesnt-work-as-expected-inside-the-tab--accordion-directive

**Comment by cdparra** [comment]
I will take a look at the end of the week, when I will have some time to play with this. Thanks for the feedback!

**Comment by enkodellc** [comment]
Made a little progress: Checkout line#240 in the multislider.js that is the only line I added: updateCalculations();
http://plnkr.co/edit/F5EPdL1dryqSGt0f1W6l?p=preview

It is definitely something to do with the rendering order of the tabs and multi-slider. I was able to get the first tab to render by adding the updateCalculations to the timeout.  From what I can guess is the offsetLeft of the tabs are not defined at that point in rendering so they need to be refreshed to properly set the CSS left of each handle and bubble. I am not sure how to make that happen for each tab... Maybe there is a function to do this for tabs or maybe some CSS or directive function that is needed to render after the parent...

**Comment by cdparra** [comment]
Linking a [SO answer](http://stackoverflow.com/a/33650816/1018418) that can help solve the issue

**Comment by enkodellc** [comment]
@cdparra Great that a solution was found. I will post it as an example for future reference. One part of me was sort of hoping there was a solution that I could update the angular-multi-slider to solve the solution to avoid any future issues with these types of parent directives but at least a solution was found and we can add it to the demo for reference.

I hope to add additional functionality that you might be interested in with a key to show all the handles and a possible collision detection to allow you to view the bubbles on top of one another but the collision one is not trivial when it comes to (n) handles and it could cause it to stack so many handles that it will not look / work great.

**Comment by cdparra** [comment]
That functionality would be great indeed. I am trying to extend your slider so that it becomes a "dates" slider/timeline and controlling collisions and avoiding handles to pass one another would be useful. I have only been using angular js for the last 6 months (and javascript for the last year and half), so I am still pretty much learning.

**Comment by enkodellc** [comment]
Updated the directive and demo to reflect changes to fix the uib-tab initial rendering issue. Thanks for bringing it to my attention.  FYI there is a time slider available but I found it difficult to use / configure. It didn't have several of the features I have and will include in mine.   Here is their repo: https://github.com/val-samonte/angular-multirange

**Comment by enkodellc** [comment]
Added a key and collision detection. Though it is not perfect for your many sliders it does a great job. Your scenario has a lot of sliders and I recommend you review the directive to see if you can improve on the initialization of the collision detection to solve. The easiest solution would be to hide the bubbles and use the Key, 
http://plnkr.co/edit/uTrlSK4R0iEhmg3mF2Cv?p=preview
