### ISSUE TITLE
is there any option for disabled?

### ISSUE THREAD

**Issue by UrVerySpecial** [enkodellc/angular-multi-slider#4]
Hi,
I am really appreciate for this module. 
I want to disabled when flag is false, is there any option?

Thanks.
kang

**Comment by enkodellc** [comment]
Are you looking to "disable" the slider from user interaction or are you looking to set the visibility to false?

**Comment by UrVerySpecial** [comment]
thanks. i think change visibility to false is better, too.

**Comment by enkodellc** [comment]
I have most of this code written to do both but it is not good enough to merge. It is posted on this plunker:
http://plnkr.co/edit/I3A9H8qTs0z4CVaYnyJZ?p=preview
