### ISSUE TITLE
Problem when using ng-hide

### ISSUE THREAD

**Issue by guilhermeartem** [enkodellc/angular-multi-slider#5]
When I use the multi-slider directive with a ng-hide property set to true in the moment of the loading of the page, it bugs out. On the firefox console i got the message "Too much recursion".

Here a [Plunkr](http://plnkr.co/edit/tBU2GDhEHnGNmE8Jzd3G?p=preview) link with the issue.

![screenshot from 2016-06-15 17-13-32](https://cloud.githubusercontent.com/assets/2971994/16095772/8de24338-331c-11e6-8b61-88f5aefdc195.png)

**Comment by enkodellc** [comment]
I was able to recreate. If the sliders are initially visible it works, just when they are initialized as hidden. I will have to review the code a bit to handle this scenario. Thanks.

**Comment by enkodellc** [comment]
Added watch for ng-Hide attribute to ignore the functionality if not there, process if visible.  I pushed the updated code to master.

You can test with this [http://plnkr.co/edit/KANz6usWwnt2MD5GpTwk?p=preview](Plunker)

**Comment by guilhermeartem** [comment]
Thank you very much!!!
