### ISSUE TITLE
binding ng-model issue based on a service response

### ISSUE THREAD

**Issue by rawanujoom** [enkodellc/angular-multi-slider#6]
changing the ng-model based on a service response is not being reflected on the slider, though the value that is binded to the slider is being updated 

while if I place the response in this scope variable from the start works well.

`<multi-slider name="dateSlider"
                                            floor="{{model.dateFloor}}"
                                            step="60"
                                            precision="2"
                                            ceiling="{{model.dateCeiling}}"
                                            bubbles="true"
                                            display-filter="date : 'shortTime'"
                                            reletiveValues="true"
                                            ng-model="model.dateSliders"
                                            style="margin-top:200px">
                              </multi-slider>
                              <multi-slider-key ng-model="model.dateSliders" display-filter="date : 'shortTime'"></multi-slider-key>`

is there a way to redraw the values? or to refresh it?

![image](https://cloud.githubusercontent.com/assets/13055436/19684627/ffdd0d54-9ac0-11e6-8ba7-f86d85279b1d.png)

this one is when I initialize the response from the start 

![image](https://cloud.githubusercontent.com/assets/13055436/19684675/3bea6800-9ac1-11e6-8ed9-13af28aa3207.png)

**Comment by enkodellc** [comment]
Have you tried researching some options found on stackoverflow? 

http://stackoverflow.com/q/20254417/1452739
http://stackoverflow.com/q/26363927/1452739
http://stackoverflow.com/q/32379918/1452739

Please create a plunkr example for me to   ##test.

**Comment by rawanujoom** [comment]
it's not about the service, The issue is in this slider that the component does not listen to the change after the setBindings first time execution,  updating the ngModel does not get reflected on the slider.. here is a simple example of what's happening 
http://plnkr.co/edit/iqOQH9C5IhjZJMosVhqO?p=preview

Note that a workaround won't do for my case which I have multi ranges on the same time slider, and I have do some edits on those spans and even deletes. 

Can we reflect the new array values on the component?

**Comment by enkodellc** [comment]
@rawanujoom, I didn't think it was the service. I just wanted to see you put an effort into determining the solution. I am not a fan of people having issues and not making an effort to fix / contribute to solve the issues.  I believe the updates I made will work. If they do not you will need to provide a more comprehensive example for me to test from. Thanks.
