### ISSUE TITLE
RangeError: Maximum call stack size exceeded with bubbles: false

### ISSUE THREAD

**Issue by OoDeLally** [enkodellc/angular-multi-slider#7]
Hello,

When using {bubbles: false} with more than 1 selector, I get the following errors on the console :
![image](https://cloud.githubusercontent.com/assets/1717629/22367476/0b60e884-e482-11e6-8faa-3fa6b885a615.png)

![image](https://cloud.githubusercontent.com/assets/1717629/22367519/56727072-e482-11e6-8b3d-5c150a5d034f.png)

This happens only with bubbles: false AND 1 selector. All other combinations (bubble:true or only 1 selector) seem to work.

Also, this doesnt seem to prevent the widget to work. I have all those errors, but the widget still works fine.

**Comment by enkodellc** [comment]
It would help to provide a plunkr example you can fork this one: http://plnkr.co/edit/uTrlSK4R0iEhmg3mF2Cv?p=preview

**Comment by enkodellc** [comment]
Updated the code to fix this.
