### ISSUE TITLE
after pushing new item to the sliders, cant move sliders

### ISSUE THREAD

**Issue by christoforosl** [enkodellc/angular-multi-slider#8]
Hi, 
If you see here:  https://plnkr.co/4LTFeJmwIVmv4myr3FEJ 

In the plunker above, when the "add another" button is clicked we are push new items to the  sliders array. We have the following issues:

1. the page is not being updated with the new slider and 
2. When we try to move a slider - any slider after adding new item - we get javascript error :
```
multislider.js:51 Uncaught TypeError: Cannot read property 'css' of undefined
    at offset (multislider.js:51)
    at multislider.js:202
    at Object.forEach (angular.js:336)
    at setHandles (multislider.js:196)
    at HTMLDivElement.onStart (multislider.js:331)
    at HTMLDivElement.eventHandler (angular.js:3298)
```
Is there something else we need to call in order to correctly update the page with the new items added by the button?  

I tried to troubleshoot this and the problem is that handles[key] and bubbles[key] return null for new items, added after page load.

Thank you.  Great component

**Comment by enkodellc** [comment]
@christoforosl  I see the issue, the html needs to be rebuilt on addition of new sliders.  I have this working and tested. Will upload the new code after debugging an error I found.

**Comment by enkodellc** [comment]
Updated the code and examples for this enhancement. You can view the plunker here: http://plnkr.co/edit/uTrlSK4R0iEhmg3mF2Cv  just make sure you review the addslider function and updated the multislider.js
