### ISSUE TITLE
slider broken when there isn't an initial value

### ISSUE THREAD

**Issue by pellicciaroberto** [enkodellc/angular-multi-slider#9]
Hi,
see here an example of problem: http://plnkr.co/edit/A6jAVqK2xcFRQYl6oIox?p=preview

If there isn't a  value for the slider, the object is viewed with the floor and ceiling on the same position

![image](https://user-images.githubusercontent.com/35963931/35571808-6d13036e-05d3-11e8-8595-38b778d46dea.png)

**Comment by enkodellc** [comment]
@pellicciaroberto  I am not sure what you are expecting it to do if you pass in bad data. Maybe you think it should be up to the control to validate the data more. Please submit a PR for the suggested fix and I will review.  Thanks.
